NUMPY

In [2]:
import numpy as np
from numpy import exp, sqrt, log, pi

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
C=np.vstacK(a,b)

# Arrays
## .arange, .linspace, .delete, .fullspace

In [19]:
# Array mit pre Werten erstellen
# np.arange(start,end,stepsize)
# end non-inclusive
np.arange(2.0,3.0,0.25)

array([2.  , 2.25, 2.5 , 2.75])

In [ ]:
# np.linspace(start,stop,num,endpoint=True)
# stop non-inclusive
np.linspace(0,1,11,endpoint=False)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [12]:
# array=np.delete(array,index(-array))
# Bsp.
U=[1,2,3,4]
np.delete(U,[0,-1])

array([2, 3])

In [15]:
#slicing np.s_
U=np.arange(1,10,1)
np.delete(U, np.s_[-3:])

array([1, 2, 3, 4, 5, 6])

In [17]:
# aus einem wert ein array mit n-mal dem gleichen wert machen
A=np.array([1,2,3,4,5])
a=1
np.full_like(A,a)

array([1, 1, 1, 1, 1])

## .vstack

In [33]:
# The array formed by stacking the given arrays, will be at least 2-D.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

## .concatenate

In [34]:
# Join a sequence of arrays along an existing axis.
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

## .sort

In [4]:
# sorting
numbers=np.array([40,30,20,10,6,3,0,-3,-6,-10,-20,-30,-40])
numbers=np.sort(numbers)
print(numbers)
# .join zum Einfügen eines Strings zwischen allen array werten
text =" & ".join(numbers.astype(str))
print(text)

[-40 -30 -20 -10  -6  -3   0   3   6  10  20  30  40]
-40 & -30 & -20 & -10 & -6 & -3 & 0 & 3 & 6 & 10 & 20 & 30 & 40


## .argmin

In [5]:
# Wert im Array finden
zielwert = 6
numbers=np.array([40,30,20,10,6,3,0,-3,-6,-10,-20,-30,-40])
index=np.abs(numbers-zielwert).argmin()
print(index)

4


# .loadtxt

In [6]:
# wenn man mehrere Dateien mit iniziertem Name speichern will, dann den Namen in Hilfsvariable festlegen
N = []
for i in range(1,5):
    # F-String f"n{i+1}.txt" (oder ohne Endung, je nach Dateinamen)
    dateiname = f"n{i}" 
    # Pfad zusammensetzen und Datei laden
    n = np.loadtxt(Messwerte_path / "Silber" / dateiname, delimiter=",", unpack=True)
    # Zur Liste hinzufügen
    N.append(n)

NameError: name 'Messwerte_path' is not defined